const API_BASE_URL_DEVELOPMENT = 'https://localhost:7242';
const API_BASE_URL_PRODUCTION = 'https://appname.azurewebsites.net';

const ENDPOINTS = {
    REGISTRATION: "Registration",
    AUTHENTICATION: "Authentication",
    UNAUTHENTICATION: "Unauthentication",
    GET_USER_DATA: "get-user-data"
};

const development = {
    API_URL_REGISTRATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.REGISTRATION}`,
    API_URL_AUTHENTICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.AUTHENTICATION}`,
    API_URL_UNAUTHENTICATION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UNAUTHENTICATION}`,
    API_URL_GET_USER_DATA: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_USER_DATA}`,
}

const production = {
    API_URL_REGISTRATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.REGISTRATION}`,
    API_URL_AUTHENTICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.AUTHENTICATION}`,
    API_URL_UNAUTHENTICATION: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UNAUTHENTICATION}`,
    API_URL_GET_USER_DATA: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_USER_DATA}`,
}

const Urls = process.env.NODE_ENV === "development" ? development : production;

export default Urls;